### ISSUE TITLE
Files.createTempFile (attachment, ".tgz")

### ISSUE THREAD

**Issue by dingdaoyi** [artipie/npm-adapter#8]
xnpm-files problem  

  1    `` `javapath = Files.createTempFile (attachment, ".tgz");`` `   

 creation error with attachment with folder   

 2.Npm preferably return  Single with attachments.keySet ().

**Comment by yegor256** [comment]
@dingdaoyi can you please explain what exactly you are doing? Can you show more code. At the moment I don't understand the question. What is wrong?

**Comment by dingdaoyi** [comment]
1、 E.g：
final Path path = Files.createTempFile("aaa/bbb.tgz", ".tgz");
exception： java.lang.IllegalArgumentException: Invalid prefix or suffix
2、
Need to upload the taz package on s3. If the file name is not returned, I need to read the temporary file to resolve the name myself.

**Comment by yegor256** [comment]
@dingdaoyi this code throws exception?

```
final Path path = Files.createTempFile("aaa/bbb.tgz", ".tgz");
```

Are you sure? Can you please post the exception stacktrace?

**Comment by dingdaoyi** [comment]
@yegor256 Exception in thread "main" java.lang.IllegalArgumentException: Invalid prefix or suffix
	at java.nio.file.TempFileHelper.generatePath(TempFileHelper.java:63)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:127)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:897)
	at com.yegor256.npm.Meta.main(Meta.java:92)

**Comment by yegor256** [comment]
@dingdaoyi there is no such method as `Meta.main` in this library. Please, show your code now. How do you use this library?

**Comment by yegor256** [comment]
@Sammers21 can you please help?

**Comment by dingdaoyi** [comment]
https://github.com/artipie/npm-adapter/blob/master/src/main/java/com/artipie/npm/Npm.java
 private Completable updateSourceArchives(
        final String prefix,
        final JsonObject uploaded
    ) {
        return Single.fromCallable(() -> uploaded.getJsonObject("_attachments"))
            .flatMapCompletable(
                attachments ->
                    Completable.concat(attachments.keySet().stream()
                        .map(
                            attachment -> {
                                final Path path;
                                try {
                                    path = Files.createTempFile(attachment, ".tgz");
                                } catch (final IOException exception) {
                                    throw new IllegalStateException(
                                        "Unable to create temp file",
                                        exception
                                    );
                                }
                                return new TgzArchive(
                                    attachments.getJsonObject(attachment).getString("data")
                                ).saveToFile(path)
                                    .andThen(
                                        this.storage.save(
                                            String.format("%s/%s", prefix, attachment),
                                            path
                                        )
                                    );
                            }
                        ).collect(Collectors.toList())
                    )
            );
    }
Files.createTempFile is used in this class, and the attachment takes the parent directory, all errors

**Comment by yegor256** [comment]
@dingdaoyi can you show _your_ code, please? How do you use the library?

**Comment by dingdaoyi** [comment]
@yegor256 


npm.publish(fileInfo.getNodePath(),
            localCacheFile.substring(localCacheFile.lastIndexOf("/") + 1))
            .subscribe(() ->observer.accept(getUploadInfoModelList(fileInfo)));

package.json:
 "name": "@ avenueui / flint1",
The attached attachments.keyset () is
"@ avenueui / flint1-1.7.5.tgz" is a file with a parent directory
{
    "_id": "@ avenueui / flint1",
    "name": "@ avenueui / flint1",
    "description": "Made out of 2SiO2",
    "dist-tags": {
        "latest": "1.7.5"
    },
    "versions": {
            
    },
    "readme": "flint",
    "maintainers": [
        {
            "name": "admin",
            "email": "user@email.com"
        }
    ],
    "_attachments": {
        "@ avenueui / flint1-1.7.5.tgz": {
            "content_type": "application / octet-stream",
            "data": "-243423432--",
            "length": 23261
        }
    }
}

Throw exception after run npm publish command

When package.json
 "name": "flint1", no problem

**Comment by Sammers21** [comment]
@dingdaoyi, that is difficult to understand what you mean. Can you provide a reproducer in the form of a test for this project([example](https://github.com/artipie/npm-adapter/blob/master/src/test/java/com/artipie/npm/NpmCommandsTest.java#L57))? Another option is to create a repository on GitHub with Main class, so anyone could reproduce it.

**Comment by dingdaoyi** [comment]
@Sammers21 @yegor256 
The easiest way, you put the simple-npm-project / package.json
"name": "simple-npm-project"
Change to
 "name": "@ aabb / simple-npm-project"
https://github.com/artipie/npm-adapter/blob/master/src/test/resources/simple-npm-project/package.json

**Comment by dingdaoyi** [comment]
java.lang.IllegalArgumentException: Invalid prefix or suffix
	at java.nio.file.TempFileHelper.generatePath(TempFileHelper.java:63)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:127)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:897)
	at com.artipie.npm.Npm.lambda$null$5(Npm.java:107)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.artipie.npm.Npm.lambda$updateSourceArchives$6(Npm.java:124)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:83)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:55)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:3693)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2279)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onComplete(SingleFlatMapCompletable.java:102)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onComplete(CompletableAndThenCompletable.java:99)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:46)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2279)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onComplete(SingleFlatMapCompletable.java:102)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:46)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2279)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:112)
	at io.reactivex.rxjava3.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:3693)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:85)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:55)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:3693)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:3693)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2279)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(CompletableAndThenCompletable.java:35)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2279)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:55)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:3693)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2279)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(CompletableAndThenCompletable.java:35)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2279)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
	at io.reactivex.rxjava3.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:55)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:3693)
	at io.reactivex.rxjava3.internal.operators.single.SingleDelayWithCompletable$OtherObserver.onComplete(SingleDelayWithCompletable.java:69)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:46)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2279)
	at io.reactivex.rxjava3.internal.operators.single.SingleDelayWithCompletable.subscribeActual(SingleDelayWithCompletable.java:36)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:3693)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2279)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:55)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:3693)
	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2279)
	at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1243)
	at com.artipie.npm.NpmRegistry.lambda$putPackage$0(NpmRegistry.java:177)
	at io.vertx.reactivex.core.http.HttpServerRequest$2.handle(HttpServerRequest.java:363)
	at io.vertx.reactivex.core.http.HttpServerRequest$2.handle(HttpServerRequest.java:361)
	at io.vertx.core.http.HttpServerRequest.lambda$bodyHandler$0(HttpServerRequest.java:216)
	at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:530)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:516)
	at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:176)
	at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:163)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:140)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Sammers21** [comment]
@dingdaoyi, ah, I got it. I will create a Pull Request to fix that.
